### PR TITLE
Bidirectional relationship fix - don't flip the direction based simpl…

### LINKED ISSUE #11: Bidirectional relationships show incorrectly on contact B
To replicate:
* Enable displaying "Spouse of" on Relationship Block.
* Add a "Spouse of" relationship from contact A to contact B.
* Contact A displays contact B as their spouse...but contact B also displays contact A as their spouse.

I'm going to take a first crack at fixing this, I'll let you know how far I get!

### PR DESCRIPTION
**Pull request by MegaphoneJon**
…y on bidirectionality
Closes #11.

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
OK - this is a bit more resistant to a fix than I'd originally hoped, so I'm opening it up to discussion.

The `getDisplayedRelationshipTypes` method returns a list of relationship types to display - including direction (`a_b` or `b_a`).  However, when building the form, you can't know which direction is valid without passing in context about the specific contact.  Of course, we want to avoid that for performance reasons - but at present, `CRM_Relationshipblock_Form_Inline_RelationshipBlock::buildQuickForm` will always display the `a_b` relationship.

**Comment by MegaphoneJon** [comment]
I took a break from this to see if that would give me clarity, but instead I just thought of another problem, which is the intersection of multiple relationships with bidirectional relationships:
* Given a bidirectional relationship "is friends with";
* Contact 1 is friends with Contact 2.  Contact 3 is friends with Contact 1.  This means Contact 1 is in the "a" position on one relationship, but the "b" relationship on another.

It would take some serious witchery to display "is friends" with in the Relationship Block on Contact 1 "correctly" and still save the records correctly.

**Comment by colemanw** [comment]
I'm really confused about what the bug is. Could you post steps to reproduce?
The reason I coded it this way is because once the relationship exists, this extension won't touch it anymore so the direction shouldn't matter.

**Comment by MegaphoneJon** [comment]
@colemanw Steps to replicate are on #11.  My WIP fix is fine for the Page but not the Form.
Knowing that the extension won't touch an existing relationship certainly eases the issue - I think my last comment is less applicable, and it means that the ultimate fix should be less complicated - but it still remains.

**Comment by colemanw** [comment]
Closed in favor of #13

**Pull request closed without merging**
