### PR TITLE
Fix template markup

### PR DESCRIPTION
**Pull request by colemanw**
Improves the markup to better match what's in core. Makes it look much nicer with Shoreditch enabled.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Cool - @colemanw I was meaning to ask. The request has come back to have a free text field (a custom field) below it for when the relationship field is not suitable but they want to describe their relationship. Do you have any thoughts about that? It feels a bit ugly from a dev POV but I guess I have to find a non-ugly way

**Comment by colemanw** [comment]
Ok so is it:

- Contact id is known but relationship_type_id is replaced with free text?

or

- Relationship_type_id is known but contact_id is free text?

or either/both?

**Comment by colemanw** [comment]
@eileenmcnaughton ^

**Comment by eileenmcnaughton** [comment]
@colemanw just sticking with a separate field for now

**Pull request merged**
